import Head from "next/head";
import React from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import activities from "../activities";
import ActivityCard from "../components/activity_card";
import ActivityExpand from "../components/activity_expand";

export default function Home() {
  const [showPopup, setShowPopup] = React.useState(false);
  const [showMenu, setShowMenu] = React.useState(false);
  const [selectedActivity, setSelectedActivity] = React.useState(activities.hits.hits)
  const [ac, setAC] = React.useState(activities.hits.hits);
  let searchText = "";
  function openPopup(item) {
    setSelectedActivity(item);
    setShowPopup(true);
  }
  function closePopup() {
    setSelectedActivity(null)
    setShowPopup(false);
  }
  function openMenu() {
    setShowMenu(!showMenu);
  }
  function processSearch(event) {
    searchText = event.target.value;
    setAC(
      activities.hits.hits.filter((b) => {
        console.log(b);
        return (
          searchText.length === 0 ||
          b._source.name.toLowerCase().includes(searchText.toLowerCase())
        );
      })
    );
  }

  return (
    <div>
      <Head>
        <title>mycheapcopy - catalogue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <nav className="navbar col-12 col-xl-10 px-3 m-auto navbar-expand-lg navbar-light  justify-content-between">
        <a className={"navbar-brand " + styles.h1} href="#">
          mycheapcopy
        </a>

        <div
          className="d-none d-xl-block collapse navbar-collapse d-flex flex-row align-items-center justify-content-between"
          id="navbarText"
        >
          <ul className="navbar-nav mr-auto col">
            <li className="nav-item">
              <a className={"nav-link " + styles.activenav} href="#">
                catalogue
              </a>
            </li>
          </ul>
          <button type="button" className={styles.cta + " col-auto"}>
            See Pricing
          </button>
        </div>
        <div className="d-block d-lg-none">
          <img src="svg/menu.svg" className={styles.materialsize+" "+styles.clickable }  onClick={() => openMenu()} />
        </div>
        {showMenu ? (
          <div className={styles.menu+" d-lg-none"}>
            <ul className="navbar-nav d-flex flex-column align-items-start justify-content-start">
              <li className="nav-item">
                <a className={"nav-link " + styles.insidemenu +" "+ styles.activenav} href="#">
                  catalogue
                </a>
              </li>
              <br />
              <li>
                <button type="button" className={styles.cta + ""}>
                  See Pricing
                </button>
              </li>
            </ul>
          </div>
        ) : (
          ""
        )}
      </nav>
      <header className={styles.header + ""}>
        <div className="col-12 col-xl-10 p-3 m-auto">
          {" "}
          <h1 className={styles.h1}>
            Your perfect work out
            <br /> is waiting for you
          </h1>
          <div
            id="searchbar-wrapper"
            className="d-flex flex-row justify-content-start align-items-center"
          >
            <form
              className={
                "form my-5 d-flex flex-row align-items-center " +
                styles.searchbar
              }
            >
              <img src="svg/search.svg" className={styles.materialsize} />
              <input
                className={"form-control mr-sm-2 " + styles.searchbarinput}
                type="search"
                onChange={(event) => processSearch(event)}
                placeholder="Search"
                aria-label="Search"
              />
            </form>
          </div>
        </div>
      </header>
     
      <main className={styles.main}>
        <section className={"col-12 col-xl-10 row mx-xl-auto" + styles.grid}>
          {ac.map((item) => (
            <ActivityCard openPopup={() => openPopup(item)} item={item} />
          ))}
        </section>
        {showPopup ? (
          <ActivityExpand closePopup={() => closePopup()} selectedActivity={selectedActivity} />
        ) : (
          ""
        )}
      </main>
    </div>
  );
}
